//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentRestaurant_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public int ProductID { get; set; }
        public int StudentID { get; set; }
        public int Rating1 { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Student Student { get; set; }
    }
}
