//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStudentRestaurant_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eStudentRestaurant_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added..
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format..
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been using by another user..
        /// </summary>
        internal static string email_ex_err {
            get {
                return ResourceManager.GetString("email_ex_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required 13 numbers..
        /// </summary>
        internal static string jmbg_err {
            get {
                return ResourceManager.GetString("jmbg_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username doesn&apos;t exist..
        /// </summary>
        internal static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfull..
        /// </summary>
        internal static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not numbers allowed..
        /// </summary>
        internal static string number_err {
            get {
                return ResourceManager.GetString("number_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To much characters..
        /// </summary>
        internal static string overflow_err {
            get {
                return ResourceManager.GetString("overflow_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains min 6 chars ( combination of numbers and letters)..
        /// </summary>
        internal static string pass_err {
            get {
                return ResourceManager.GetString("pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose an image of larger dimensions..
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields are empty..
        /// </summary>
        internal static string Required_Error {
            get {
                return ResourceManager.GetString("Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username has been using by another user..
        /// </summary>
        internal static string username_ex_err {
            get {
                return ResourceManager.GetString("username_ex_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
